---
abstract: 'App::financeta is a Technical Analysis GUI'
author:
  - 'Vikas N. Kumar <vikas@cpan.org>'
build_requires:
  File::ShareDir: 0
  File::Spec: 0
  Module::Build: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4207, CPAN::Meta::Converter version 2.132661'
keywords:
  - finance
  - technical-analysis
  - technical
  - analysis
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-financeta
no_index:
  directory:
    - t
    - share
provides:
  App::financeta:
    file: lib/App/financeta.pm
    version: 0.10
  App::financeta::editor:
    file: lib/App/financeta/editor.pm
    version: 0.10
  App::financeta::gui:
    file: lib/App/financeta/gui.pm
    version: 0.10
  App::financeta::indicators:
    file: lib/App/financeta/indicators.pm
    version: 0.10
  App::financeta::language:
    file: lib/App/financeta/language.pm
    version: 0.10
  App::financeta::language::grammar:
    file: lib/App/financeta/language.pm
    version: 0.10
  App::financeta::language::receiver:
    file: lib/App/financeta/language.pm
    version: 0.10
  App::financeta::mo:
    file: lib/App/financeta/mo.pm
    version: 0.1
requires:
  Browser::Open: 0
  Capture::Tiny: 0
  Carp: 0
  Data::Dumper: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  File::HomeDir: 0
  File::Path: 0
  File::ShareDir: 1.00
  File::Spec: 0
  Finance::QuoteHist: 1.2
  Getopt::Long: 0
  PDL: 2.007
  PDL::Finance::TA: 0.008
  PDL::Graphics::Gnuplot: 0
  POE::Loop::Prima: 0
  POSIX: 0
  Pegex: 0.55
  Prima: 1.40_1
  Scalar::Util: 0
  YAML::Any: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/vikasnkumar/financeta/issues
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
  repository: https://github.com/vikasnkumar/financeta
version: 0.10
